version: '3'

services:
  consensus_on_demand:
    build:
      context: .
      dockerfile: Dockerfile
    image: consensus_on_demand:latest
    command: ["--r", $REPLICA_NUMBER, "--n", $TOTAL_REPLICA_NUMBER, "--f", $FAULTY_REPLICAS, "--p", $DISAGREEING_REPLICA, "--t", $EXECUTION_TIME, "--d", $NOTARIZATION_DELAY, $COD, "--p2=", $P2, "--p3=", $P3]
    ports:
      - "56789:56789"
    volumes:
      - ./benchmark:/replica/benchmark
